<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Game;
use Illuminate\Support\Facades\DB;

class GameSeeder extends Seeder
{
    public function run()
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        
        // Clear existing games
        Game::truncate();
        
        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $games = [
            [
                'title' => 'Cyberpunk 2077',
                'description' => 'An open-world, action-adventure RPG set in the megalopolis of Night City',
                'developer' => 'CD Projekt Red',
                'category' => 'RPG',
                'price' => 299000,
                'release_date' => '2020-12-10',
                'stock' => 50,
                'rating' => 4.5,
                'file_url' => '/games/cyberpunk2077.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7r.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Witcher 3: Wild Hunt',
                'description' => 'A story-driven, open world adventure set in a dark fantasy universe',
                'developer' => 'CD Projekt Red',
                'category' => 'RPG',
                'price' => 199000,
                'release_date' => '2015-05-19',
                'stock' => 75,
                'rating' => 4.9,
                'file_url' => '/games/thewitcher3.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7q.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Grand Theft Auto V',
                'description' => 'An action-adventure game played from either a third-person or first-person perspective',
                'developer' => 'Rockstar Games',
                'category' => 'Action',
                'price' => 249000,
                'release_date' => '2013-09-17',
                'stock' => 60,
                'rating' => 4.7,
                'file_url' => '/games/gtav.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7s.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'description' => 'An epic tale of life in America\'s unforgiving heartland',
                'developer' => 'Rockstar Games',
                'category' => 'Adventure',
                'price' => 399000,
                'release_date' => '2018-10-26',
                'stock' => 45,
                'rating' => 4.8,
                'file_url' => '/games/reddead2.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7t.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Counter-Strike 2',
                'description' => 'The largest technical leap forward in Counter-Strike\'s history',
                'developer' => 'Valve',
                'category' => 'Action',
                'price' => 0,
                'release_date' => '2023-09-27',
                'stock' => 999,
                'rating' => 4.6,
                'file_url' => '/games/cs2.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7u.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FIFA 24',
                'description' => 'The latest installment in the FIFA football simulation series',
                'developer' => 'EA Sports',
                'category' => 'Sports',
                'price' => 599000,
                'release_date' => '2023-09-29',
                'stock' => 80,
                'rating' => 4.2,
                'file_url' => '/games/fifa24.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7v.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Call of Duty: Modern Warfare III',
                'description' => 'The direct sequel to the record-breaking Call of Duty: Modern Warfare II',
                'developer' => 'Infinity Ward',
                'category' => 'Action',
                'price' => 699000,
                'release_date' => '2023-11-10',
                'stock' => 55,
                'rating' => 4.3,
                'file_url' => '/games/mw3.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7w.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Minecraft',
                'description' => 'A sandbox game where players build with blocks in a 3D world',
                'developer' => 'Mojang Studios',
                'category' => 'Adventure',
                'price' => 199000,
                'release_date' => '2011-11-18',
                'stock' => 200,
                'rating' => 4.8,
                'file_url' => '/games/minecraft.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7x.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Sims 4',
                'description' => 'A life simulation game that allows players to create and control people',
                'developer' => 'Maxis',
                'category' => 'Simulation',
                'price' => 0,
                'release_date' => '2014-09-02',
                'stock' => 150,
                'rating' => 4.1,
                'file_url' => '/games/sims4.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7y.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Resident Evil 4 Remake',
                'description' => 'A reimagining of the genre-defining classic Resident Evil 4',
                'developer' => 'Capcom',
                'category' => 'Horror',
                'price' => 499000,
                'release_date' => '2023-03-24',
                'stock' => 40,
                'rating' => 4.7,
                'file_url' => '/games/re4remake.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7z.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Stardew Valley',
                'description' => 'An open-ended country-life RPG with farming, relationships, and exploration',
                'developer' => 'ConcernedApe',
                'category' => 'Simulation',
                'price' => 149000,
                'release_date' => '2016-02-26',
                'stock' => 100,
                'rating' => 4.9,
                'file_url' => '/games/stardewvalley.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r80.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Among Us',
                'description' => 'An online multiplayer social deduction game set in space',
                'developer' => 'InnerSloth',
                'category' => 'Puzzle',
                'price' => 49000,
                'release_date' => '2018-06-15',
                'stock' => 300,
                'rating' => 4.0,
                'file_url' => '/games/amongus.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r81.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rocket League',
                'description' => 'A vehicular soccer video game with rocket-powered cars',
                'developer' => 'Psyonix',
                'category' => 'Sports',
                'price' => 0,
                'release_date' => '2015-07-07',
                'stock' => 250,
                'rating' => 4.5,
                'file_url' => '/games/rocketleague.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r82.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hades',
                'description' => 'A rogue-like dungeon crawler in which you defy the god of the dead',
                'developer' => 'Supergiant Games',
                'category' => 'Indie',
                'price' => 199000,
                'release_date' => '2020-09-17',
                'stock' => 65,
                'rating' => 4.8,
                'file_url' => '/games/hades.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r83.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forza Horizon 5',
                'description' => 'An open world racing game set in a fictional representation of Mexico',
                'developer' => 'Playground Games',
                'category' => 'Racing',
                'price' => 599000,
                'release_date' => '2021-11-09',
                'stock' => 70,
                'rating' => 4.7,
                'file_url' => '/games/forza5.zip',
                'image_url' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r84.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Game::insert($games);

        $this->command->info('Games seeded successfully!');
        $this->command->info('Total games: ' . count($games));
    }
}